extraction:
  cpp:
    after_prepare: 
      - python report.py 97
  cobol:
    after_prepare: 
      - python report.py 97
  csharp:
    after_prepare: 
      - python report.py 97
  java:
    after_prepare: 
      - python report.py 97
  javascript:
    after_prepare: 
      - python report.py 97
  python:
    after_prepare: 
      - python report.py 97
